// Map glyph asset registry — the hand-authored vector icon SET for the Pixi map
// stage (Task 12.5; design/phase-12/stage-1-design.md §3.2, §9.5).
//
// These are NOT the Claude-Design product (free-form SVG drifts in stroke/style
// across a set). They are generated by Claude Code against a LOCKED STYLE-SPEC so
// the set stays visually cohesive:
//
//   LOCKED STYLE-SPEC
//   • viewBox        — `0 0 24 24` on EVERY asset (one convention)
//   • intrinsic size — 48×48 (2× the 24-unit grid)
//   • grid unit      — 24×24 ({@link GLYPH_VIEWBOX}), content within a ~3px margin
//   • stroke weight  — 2 (1.7 for fine internal slats / orbits), round cap+join
//   • corner radius  — 3–3.5 on enclosing rects
//   • geometry       — geometric / line only; no gradients, no text, no raster
//   • palette        — authored in WHITE (#FFFFFF) so the Pixi layer can TINT each
//                      glyph to an identity colour or a status token at render time
//                      (white source × tint = the target colour).
//
// The single source of every COLOUR a glyph is tinted to is `tokens.ts` (via
// `pixiHex`) — zero colour constants here beyond the white source.
//
// PIPELINE — loaded into Pixi as VECTOR, not raster. Each `.svg` is imported as
// its source string (Vite `?raw`) and drawn into a `Graphics` node with
// `Graphics.svg()` (see {@link paintGlyph}), so it renders through the same GPU
// geometry path as the rooms/tokens — reliable in every renderer, and crisp at
// any zoom (the task's "vector Pixi"). No image-texture upload is involved.

import type { Graphics } from "pixi.js";

import body from "./body.svg?raw";
import idle from "./idle.svg?raw";
import impostor from "./impostor.svg?raw";
import kill from "./kill.svg?raw";
import lights from "./lights.svg?raw";
import moving from "./moving.svg?raw";
import reactor from "./reactor.svg?raw";
import report from "./report.svg?raw";
import sabotage from "./sabotage.svg?raw";
import task from "./task.svg?raw";
import vent from "./vent.svg?raw";

import type { AgentAction } from "../../types/api";

// Every glyph SVG shares one viewBox unit (the locked style-spec) — the painter
// scales the parsed vector geometry from this grid into screen pixels.
export const GLYPH_VIEWBOX = 24;

// One entry per asset file under this directory, keyed by a stable glyph name; the
// value is the raw SVG source (Vite `?raw`), parsed into Pixi geometry on demand.
export const GLYPH_SVG = {
  idle,
  moving,
  task,
  kill,
  vent,
  report,
  sabotage,
  body,
  reactor,
  lights,
  impostor,
} as const;

export type GlyphName = keyof typeof GLYPH_SVG;

// The render-ready `current_action` → action glyph mapping (DESIGN.md §3.2: the
// engine already collapses `report`/`emergency`→REPORT and `repair_sabotage`→TASK
// before this DTO field, so the seven AgentAction values map 1:1 to a glyph).
export const ACTION_GLYPH: Record<AgentAction, GlyphName> = {
  IDLE: "idle",
  MOVING: "moving",
  TASK: "task",
  KILL: "kill",
  VENT: "vent",
  REPORT: "report",
  SABOTAGE: "sabotage",
};

// Re-parsing the SVG geometry on every @pixi/react redraw would be wasteful, so
// each `Graphics` node remembers the glyph it last parsed; only a CONTENT change
// (an agent's action flips) re-parses. Position / scale / tint update every draw
// (cheap). Keyed on the node so it auto-cleans when the node is GC'd.
const lastParsed = new WeakMap<Graphics, string>();

/**
 * Paint a glyph onto a `Graphics` node: draw the white vector SVG centred at
 * (cx, cy), scaled to `size` px and tinted to a token colour. Draws onto the
 * node's OWN context (not a shared one), which is the path @pixi/react renders.
 */
export function paintGlyph(
  g: Graphics,
  svg: string,
  cx: number,
  cy: number,
  size: number,
  tint: number,
  alpha = 1,
): void {
  if (lastParsed.get(g) !== svg) {
    g.clear();
    g.svg(svg);
    lastParsed.set(g, svg);
  }
  const s = size / GLYPH_VIEWBOX;
  g.scale.set(s);
  g.position.set(cx - (GLYPH_VIEWBOX / 2) * s, cy - (GLYPH_VIEWBOX / 2) * s);
  g.tint = tint;
  g.alpha = alpha;
}
